version: "3"
services:
  backend:
    build:
      context: ./backend
    restart: on-failure
    env_file: conf.ini
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.federator.rule=Host(`federator.malaclypse.eriizu.fr`)"
      - "traefik.http.routers.federator.entrypoints=websecure"
      - "traefik.http.routers.federator.tls.certresolver=le"
      - "traefik.http.services.federator.loadbalancer.server.port=9000"
  backend_dev: 
    build:
      context: ./backend_dev
    restart: on-failure
    env_file: conf.ini
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.federator-dev.rule=Host(`federator-dev.malaclypse.eriizu.fr`)"
      - "traefik.http.routers.federator-dev.entrypoints=websecure"
      - "traefik.http.routers.federator-dev.tls.certresolver=le"
      - "traefik.http.services.federator-dev.loadbalancer.server.port=9000"
