version: "3.3"

services:
  traefik:
    image: "traefik:picodon"
    container_name: "traefik"
    network_mode: host
    restart: always
    volumes:
      - "./traefik:/etc/traefik:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
  whoami:
    image: "containous/whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.capuchon.eriizu.fr`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=le"

  youtube-dl:
    image: "kmb32123/youtube-dl-server"
    volumes:
      - /srv/ftp/videos:/youtube-dl
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ytdl.rule=Host(`ytdl.capuchon.eriizu.fr`)"
      - "traefik.http.routers.ytdl.entrypoints=websecure"
      - "traefik.http.routers.ytdl.tls.certresolver=le"
      - "traefik.http.services.ytdla.loadbalancer.server.port=8080"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30

  sftp:
    build:
      context: /home/exploit/sftp
      dockerfile: Dockerfile-alpine
    volumes:
      - /srv/upload:/home/public/upload
    ports:
      - "2222:22"
    command: public:lingette:1001
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.sftp.entrypoints=sftp"
      - "traefik.tcp.services.sftp.loadbalancer.server.port=22"
  # drive:
  #   image: cozy/cozy-stack:latest
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.drive.rule=Host(`drive.capuchon.eriizu.fr`)"
  #     - "traefik.http.routers.drive.entrypoints=websecure"
  #     - "traefik.http.routers.drive.tls.certresolver=le"
  #     - "traefik.http.services.ytdla.loadbalancer.server.port=8080"
  # ftp:
  #   image: fauria/vsftpd
  #   container_name: ftp
  #   ports:
  #     - "20:20"
  #     - "21:21"
  #     - "21100-21110:21100-21110"
  #   environment:
  #     - "FTP_USER=exploit"
  #     - "FTP_PASS=lingette"
  #     - "PASV_ADDRESS=91.165.50.197"
  #     - "PASV_MIN_PORT=21100"
  #     - "PASV_MAX_PORT=21110"
  #   volumes:
  #     - /srv/ftp/videos:/home/vsftpd
  # webhook:
  #   image: "almir/webhook"
  #   container_name: "webhook"
  #   restart: always
  #   command: ["-hooks=/etc/webhook.conf.json", "-hotreload", "-verbose"]
  #   volumes:
  #     - "./webhook.conf.json:/etc/webhook.conf.json"
  #     - "/home/exploit/federator/:/projects/federator"
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.hooks.rule=Host(`hooks.capuchon.eriizu.fr`)"
  #     - "traefik.http.routers.hooks.entrypoints=websecure"
  #     - "traefik.http.routers.hooks.tls.certresolver=le"
  #     - "traefik.http.services.hooks.loadbalancer.server.port=9000"
