[http]
  [http.routers]

    [http.routers.traefik]
    rule        = "Host(`traefik.malaclypse.eriizu.fr`)"
    service     = "api@internal"
    middlewares = ["adm-auth"]
    entryPoints = ["websecure"]

      [http.routers.traefik.tls]
      certResolver = "le"

    [http.routers.insecure]
    # Redicrect insecure http trafic.
    rule        = "hostregexp(`{host:.+}`)"
    service     = "api@internal"
    middlewares = ["secure-redirect"]
    entryPoints = ["web"]


  [http.middlewares]
      [http.middlewares.adm-auth.digestAuth]
      usersFile = "/etc/traefik/pass"

      [http.middlewares.secure-redirect.redirectScheme]
      # Redicrect insecure http trafic.
      scheme = "https"
