[providers]
  [providers.docker]
  useBindPortIP    = true
  exposedbydefault = "false"

  [providers.file]
  watch    = true
  filename = "/etc/traefik/dyn.toml"

[entryPoints]
  [entryPoints.web]
  address = ":80"

  [entryPoints.websecure]
  address = ":443"

  [entryPoints.sftp]
  address = ":2222"

[accessLog]

[pilot]
token = "c122898e-e7f2-4f93-b42f-05673d01daaa"

[api]
dashboard = true
debug     = true


[certificatesResolvers]
  [certificatesResolvers.le]
    [certificatesResolvers.le.acme]
    # caserver="https://acme-staging-v02.api.letsencrypt.org/directory"
    email   = "elise.ph@icloud.com"
    storage = "/letsencrypt/acme.json"

    # [certificatesResolvers.le.acme.dnsChallenge]
    #   provider="ovh"

      [certificatesResolvers.le.acme.httpChallenge]
      entryPoint = "web"
